name: apple_shop
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: GR
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
    - family: GM
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
    - family: GB
      fonts:
        - asset: assets/fonts/GilroyBold.ttf
    - family: GEB
      fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
    - family: GH
      fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
    - family: SB
      fonts:
        - asset: assets/fonts/ShabnamBold.ttf
